// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_middleware from "./routes/_middleware.ts";
import * as $course_slug_ from "./routes/course/[slug].tsx";
import * as $courses_index from "./routes/courses/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $play_moduleId_ from "./routes/play/[moduleId].tsx";
import * as $play_moduleId_lessonId_ from "./routes/play/[moduleId]/[lessonId].tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $_middleware,
    "./routes/course/[slug].tsx": $course_slug_,
    "./routes/courses/index.tsx": $courses_index,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/play/[moduleId].tsx": $play_moduleId_,
    "./routes/play/[moduleId]/[lessonId].tsx": $play_moduleId_lessonId_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
