// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_video_auth from "./routes/api/video-auth.ts";
import * as $certification_slug_ from "./routes/certification/[slug].tsx";
import * as $certifications_index from "./routes/certifications/index.tsx";
import * as $course_slug_moduleSlug_ from "./routes/course/[slug]/[moduleSlug].tsx";
import * as $course_slug_index from "./routes/course/[slug]/index.tsx";
import * as $courses_index from "./routes/courses/index.tsx";
import * as $dataset_slug_ from "./routes/dataset/[slug].tsx";
import * as $datasets_index from "./routes/datasets/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $my_certifications from "./routes/my-certifications.tsx";
import * as $my_tracks from "./routes/my-tracks.tsx";
import * as $play_courseSlug_moduleSlug_lessonSlug_ from "./routes/play/[courseSlug]/[moduleSlug]/[lessonSlug].tsx";
import * as $profile from "./routes/profile.tsx";
import * as $tech_slug_ from "./routes/tech/[slug].tsx";
import * as $technologies_index from "./routes/technologies/index.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/video-auth.ts": $api_video_auth,
    "./routes/certification/[slug].tsx": $certification_slug_,
    "./routes/certifications/index.tsx": $certifications_index,
    "./routes/course/[slug]/[moduleSlug].tsx": $course_slug_moduleSlug_,
    "./routes/course/[slug]/index.tsx": $course_slug_index,
    "./routes/courses/index.tsx": $courses_index,
    "./routes/dataset/[slug].tsx": $dataset_slug_,
    "./routes/datasets/index.tsx": $datasets_index,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/my-certifications.tsx": $my_certifications,
    "./routes/my-tracks.tsx": $my_tracks,
    "./routes/play/[courseSlug]/[moduleSlug]/[lessonSlug].tsx":
      $play_courseSlug_moduleSlug_lessonSlug_,
    "./routes/profile.tsx": $profile,
    "./routes/tech/[slug].tsx": $tech_slug_,
    "./routes/technologies/index.tsx": $technologies_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
