// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $certification_slug_ from "./routes/certification/[slug].tsx";
import * as $certifications_index from "./routes/certifications/index.tsx";
import * as $course_slug_ from "./routes/course/[slug].tsx";
import * as $courses_index from "./routes/courses/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $mod_slug_ from "./routes/mod/[slug].tsx";
import * as $play_moduleSlug_lessonSlug_ from "./routes/play/[moduleSlug]/[lessonSlug].tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/certification/[slug].tsx": $certification_slug_,
    "./routes/certifications/index.tsx": $certifications_index,
    "./routes/course/[slug].tsx": $course_slug_,
    "./routes/courses/index.tsx": $courses_index,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/mod/[slug].tsx": $mod_slug_,
    "./routes/play/[moduleSlug]/[lessonSlug].tsx": $play_moduleSlug_lessonSlug_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
